/*
 * @Author: SUN
 * @Date: 2022-06-13 15:47:46
 * @LastEditors: SUN
 * @LastEditTime: 2022-06-15 10:03:42
 * @FilePath: \package\__tests__\__helpers__\p7.js
 */
/**
 * DO NOT EDIT THIS FILE
 */

const companies = [
  { id: 1, name: 'fox' },
  { id: 3, name: 'cloak and stagger' },
  { id: 2, name: 'cia' },
]

const status = { time: new Date().toISOString(), ok: true }

const users = [
  { name: 'fran', companyId: 3 },
  { name: 'stan', companyId: 2 },
  { name: 'steve', companyId: 1 },
]

const services = {
  fetchStatus: () => new Promise(resolve => setTimeout(() => resolve(status), 110)),
  fetchUsers: () => new Promise(resolve => setTimeout(() => resolve(users), 100)),
  fetchCompanyById: companyId =>
    new Promise(resolve =>
      setTimeout(() => resolve(companies.find(({ id }) => id === companyId)), 50)),
}

module.exports = {
  companies,
  status,
  users,
  services,
}
